Firefox: fix wrong selection with double click
ianstormtaylor/slate pull request #3374
Opened 2019-12-21 22:47 UTC by cvlmtg

#### Is this adding or improving a _feature_ or fixing a _bug_?

bugfix

#### What's the new behavior?

on firefox, when double clicking on a word which is a whole node, the selection is adjusted so that an inline style can be applied correctly

#### How does this change work?

on firefox, when the selection isn't collapsed, the range is adjusted so that:
1) if the anchor is on the end edge of a node, it is moved to the start of the next node
2) if the focux is on the start of a node, it is moved to the end of the previous node

this makes the range match what happens and chrome and avoid applying inline styles to unselected text

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #3336
Reviewers: @ianstormtaylor

2019-12-21 23:04 UTC, cvlmtg commented
@ianstormtaylor I noticed that even if I select backward, anchor always comes before focus. Not sure if this is a bug or a feature, so currently my change assumes anchor always comes before focus... Tell me if I have to check for ordering.

2019-12-25 10:12 UTC, sirgru commented
Anchor being before focus is a bug. https://github.com/ianstormtaylor/slate/issues/3333 . It would probably be better to use `start` and `end` from Range on the selection, instead of using anchor and focus.

2020-04-26 05:50 UTC, CameronAckermanSEL commented
Hi @cvlmtg , I know I'm looking at this PR like 4 months after you posted it but wanted to let you know that I merged in a PR that should have fixed the anchor/focus ordering issue, and this may have impacted your PR. Let me know when you've had an opportunity to take a look and I'll rereview the PR.

Thanks so much for the contribution!

2020-04-26 19:24 UTC, cvlmtg commented
Hi @CameronAckermanSEL, thanks for the update. Not sure if I'll be able to check it right now, but I'll try to do some tests sooner or later. Glad to see work has resumed on slate :)

2020-07-22 21:05 UTC, slotterbackW commented
Hi @cvlmtg, sorry to push, but any update on this PR? I'm happy to help test if you need it!

2021-05-06 19:00 UTC, cortopy commented
@sirgru since the bug mentioned is already fixed, what else needs to be fixed for this PR to merge?

2021-08-06 13:57 UTC, dylans requested changes
@cvlmtg please let us know if this is still relevant. if so it needs a rebase and a changeset. If not, feel free to close it. Thanks!

2021-08-13 11:01 UTC, dylans commented
Closing due to inactivity and relative staleness of the PR. Feel free to reopen if this was a mistake. Thanks!

2021-08-13 11:01 UTC, closed without merging

2022-03-22 09:56 UTC, Jawell commented
What about merging this fix? This issue is still relevant
![Untitled](https://user-images.githubusercontent.com/21054523/159454623-20cd456b-f39e-4b0f-8e9c-6181b261c650.gif)

2022-03-22 15:04 UTC, dylans commented
> What about merging this fix? This issue is still relevant
> ![Untitled](https://user-images.githubusercontent.com/21054523/159454623-20cd456b-f39e-4b0f-8e9c-6181b261c650.gif)

It sat inactive for a year and needed a rebase and ideally a test. I would be happy to review and land a PR.