Changed selection reconciliation in the React Editor to work with zero width characters added to void elements.
ianstormtaylor/slate pull request #3542
Opened 2020-03-07 10:54 UTC by ryanmitts

Void elements are selected by the insertion of a zero-width character
that the browser can select.

Currently, the selection reconciliation (making sure the Slate selection
state matches the DOM) will only select things that are within the
Editor it is responsible for, and the DOM element that is the target of
the selection is editable in the editor.

A lot of times, void nodes have their rendered root elements marked as not
content editable, thus making this zero-width character not marked as
editable, and the selection reconciliation will not mark the selection as
allowed.

A way around this is to always have an inner element in a void node
that is marked as not content editable if needed, leaving the zero-width
character out of the wrapping. This adds an unneeded DOM node however
and might get confusing without being explicit in the documentation.

This creates a new check if a node is selectable. Being selectable
means its editable or a void nodes zero-width element.

#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixing a bug, #3518 

#### What's the new behavior?

The expected behavior of the ticket. Also see the above description.

#### How does this change work?

See above description.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #3518 
Reviewers: @

2020-03-08 06:35 UTC, CameronAckermanSEL commented
Hey @ryanmitts , thanks so much for fixing this bug! 

When I was testing this, it looks like the images in the image example is no longer focusable (the cursor just skips them entirely(, which is interesting because the mentions still are. Do you think that people will want to have the image be focusable? Is there a way to accomplish that after this change?

2020-03-08 06:36 UTC, ryanmitts commented
@CameronAckermanSEL Interesting, I'll give it a look, I tested out the image example, but I'll give it another look. Is it just using the arrow keys or mouse too?

2020-03-08 06:37 UTC, CameronAckermanSEL commented
It was specifically using arrow keys (up, down arrow)

2020-03-08 06:51 UTC, ryanmitts commented
@CameronAckermanSEL Looks like there is a couple of issue with selecting void nodes, I'll try to take a look when I have time. For instance, selecting across a void node (mention or image) with the mouse.

2020-03-10 05:35 UTC, nahumzs commented
![2020-03-09 21 29 26](https://user-images.githubusercontent.com/19418590/76282755-e3b12100-6255-11ea-840f-0c7d9404141d.gif)
using  `"slate-react": "^0.57.1"` if the element is void (ex. mention) the useFocus and useSelect is always true whenever the user is on the same paragraphs, can this be part of the same bug or its completely another thing?

2021-08-07 17:36 UTC, dylans requested changes
Is this PR still relevant? @ryanmitts let me know if you have an update or if Slate already fixed this or if I should just close it out. Thanks.

2021-09-07 11:50 UTC, dylans commented
It looks like this was resolved in #3572. If I'm incorrect, feel free to reopen and rebase against main. Thanks!

2021-09-07 11:50 UTC, closed without merging