Add edge case in normalize to prevent excessive remove_node
ianstormtaylor/slate pull request #3602
Opened 2020-04-09 17:32 UTC by pzhine

#### Is this adding or improving a _feature_ or fixing a _bug_?
Fixes #3600

#### What's the new behavior?
When ENTER key is pressed after marked text (e.g. bold, italics), cursor advances to the following line and mark is maintained, as expected.

#### How does this change work?
An edge case was added to the `normalizeNode` method, which by design cleans up empty nodes. The edge case prevents this cleanup if the current editor focus is on the empty node. This is the case when a `split_node` happens after an ENTER key press when the focus was at the end of a node. See video in #3600 for broken behavior and video below for corrected behavior.

![fix](https://user-images.githubusercontent.com/2692844/78923628-d4153a00-7a98-11ea-97ba-f33995297459.gif)

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

2020-04-17 14:17 UTC, majelbstoat commented
It would be cool to see a failing test that this fixed.

2020-04-26 06:12 UTC, CameronAckermanSEL commented
@pzhine Thanks so much for the PR! Really appreciate it. This looks like it'll be a nice behavior to fix. 
I do agree with @majelbstoat though, it'd be nice to have a test case for this if we can because it'll let us prevent this bug in the future.

Thanks!

2020-05-10 15:44 UTC, pzhine commented
@majelbstoat @CameronAckermanSEL 
Test should be good to go. Run it on `master` to see it failing.

2020-05-10 17:15 UTC, majelbstoat commented
Confirmed that this test fails on master@a1ce4477 👍

2020-05-11 16:36 UTC, CameronAckermanSEL commented
Thanks @pzhine . This looks great! I'm planning on merging it and releasing it sometime this week. :)

2020-05-15 18:35 UTC, rskopal commented
I think there is a problem with this solution. If you return back to the original position after the split and press a DELETE key, the previous node is deleted:
![slate-pr3602-problem](https://user-images.githubusercontent.com/28902042/82084106-16aae180-96eb-11ea-94d2-24d0f26b0016.gif)

2020-05-16 16:44 UTC, pzhine commented
Ah, good catch @rskopal ! I'll look into that shortly

2020-11-30 07:22 UTC, spocke commented
I don't think this should be fixed in the normalizer like this the problem is in splitNodes.

This line can be changed to path ref to the parent element:
https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/transforms/node.ts#L717

Then this could be changed to as Editor.start on that path:
https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/transforms/node.ts#L756

This way the caret will be moved over to the next line when split at the selection.

The next thing is to use the pending editor marks state so when you start typing the new text will be in that previous marks before the enter was pressed. This should probably go into insertBreak:
https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/create-editor.ts#L147

Something like:
```
let marks = editor.marks;
Transforms.splitNodes(editor, { always: true })
editor.marks = marks;
```

But maybe it's not something everyone would want to it might be a thing to leave up to the implementation.

2021-08-07 15:36 UTC, dylans requested changes
Is there interest in addressing the feedback in https://github.com/ianstormtaylor/slate/pull/3602#issuecomment-735603123 or should we close this one?

2021-09-02 11:41 UTC, dylans commented
The underlying issue of this PR appears to have already been fixed, so I'm closing this out. Feel free to reopen if I missed a scenario where this is still an issue.

2021-09-02 11:41 UTC, closed without merging