Only normalize once per call to normalizeNode
ianstormtaylor/slate pull request #3690
Opened 2020-05-18 13:48 UTC by pzhine

#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixes #3689

#### What's the new behavior?

`editor.normalizeNode` loops over the children of the node and looks for normalization criteria. Currently, the loop continues even after normalization has happened. It updates the array index after the normalization (e.g. decrements if a child was merged or removed), but the array still points to the original, unmutated node children. This causes problems when the next normalization occurs because it is applied to the wrong node.

One option is to re-sync the array at the end of each iteration of the loop. However, this caused several tests to fail. Instead, we bail out of the loop after the first normalization. This solution passes all the tests, and it should be sufficient because `normalizeNode` is itself [called in the loop that iterates over "dirty" paths](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/interfaces/editor.ts#L762). In other words, if there are multiple normalizations needed on a node, the node should have multiple entries in `DIRTY_PATHS`.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

2020-05-21 01:50 UTC, TheSpyder commented
Your commit history in this PR is quite weird. Looks like a merge gone wrong. Can I suggest a `git rebase -i upstream/master` and delete everything except the commit you meant to include in the PR?

2020-05-21 02:07 UTC, TheSpyder commented
As for the fix itself, there don't appear to be any tests for nodes that require multiple normalisations when the document is first loaded? The `DIRTY_PATHS` logic you mentioned would only apply to changes during editing, as far as I understand.

2020-08-25 13:18 UTC, BrentFarese commented on packages/slate/src/create-editor.ts
> +          break
Why all the `break` statements?  The point of the loop is to continue and to use `n` to keep track of removed or added nodes so it points to the right index/node.  Was there a bug you experienced with this code as it is?

2021-08-07 16:51 UTC, dylans requested changes
This is going to need more explanation to address the previously provided feedback (now over a a year old), and it's stale.

If you have interest in revisiting this please rebase and update. Otherwise I'll close in a week or so.

2021-08-13 11:00 UTC, dylans commented
Closing due to inactivity and relative staleness of the PR. Feel free to reopen if this was a mistake. Thanks!

2021-08-13 11:00 UTC, closed without merging