Lp native single character inserts
ianstormtaylor/slate pull request #3888
Opened 2020-09-25 19:58 UTC by bkrausz

See #3293, which hasn't seen any action despite a change request. This takes that PR and makes TextString a functional component, the one requested change.

Huge thanks to @luddep for doing almost all of the work here.

#### Does this fix any issues or need any specific reviewers?
Fixes: #2061 (and some of #2051?)
Reviewers: @ianstormtaylor

2020-11-25 04:27 UTC, maccman commented
This spell-checking bug essentially makes Slate unusable in production in my opinion.

I know Slate has some new core-contributors - I urge them to look at this PR.

2020-12-02 19:58 UTC, maccman commented
Here's my hacky workaround I'm using for now:

```  const [spellCheck, setSpellCheck] = useState(true)
  const debouncedSetSpellCheck = useMemo(() => debounce(setSpellCheck, 300), [])

  const toggleSpellCheck = () => {
    // Slate has a spell checking bug where spell checking gets invoked too
    // aggressively. We can work around this by toggling it when the user types.
    // https://rb.gy/qycfpa
    setSpellCheck(false)
    debouncedSetSpellCheck(true)
  }
```

And:

```        <Slate
          onChange={newValue => {
              toggleSpellCheck()
            }
          }}>

          <EditablePlugins
            spellCheck={spellCheck}```

2020-12-07 21:42 UTC, ianstormtaylor reviewed
Looks good to me generally. It just needs someone to verify that this doesn't break other things, since this is a pretty core change.

2020-12-07 22:27 UTC, bkrausz commented
I've been using this in production on a fork for months now with no issues, though all of our users are on Chrome.

The only issue I found was in doing complex normalizations on top of nativeOps, I just fixed that via the latest commit (only required an extra `withoutNormalization`.

Is there other verification you would like to see?

2020-12-12 18:55 UTC, luddep commented
If you want to cherry-pick d7e444ab54d445d16b44b3471cf22831eb7752c6, it solves a macOS chrome bug where a long press to select a special character (hold a + press 4 = ä) would double insert until native events flushed -- solved for now by just sidestepping it entirely and limiting native events to single char a-z inserts. In my limited testing, those are the only keyboard events (on US keyboards) that trigger spell check corrections.

2021-05-06 21:12 UTC, MohsenElgendy commented
Is there an estimation on when would this PR be merged with the master?

2021-07-30 14:58 UTC, cmditch commented
Very glad a fix for the spellcheck flicker is out there. Appreciate the work @ryanmitts, @luddep, @bkrausz have put towards this. 🎉 

Pretty excited for this fix to get merged.

@thesunny do you see any issues with the logic of this PR?

2021-08-04 13:59 UTC, dylans requested changes
I hate to ask @bkrausz given how long this PR (and its previous form have been going), but if you could rebase it against the latest in main, I will get this landed asap. If you don't have time I'll do the rebase.

2021-08-06 00:41 UTC, bkrausz commented
@dylans done. I'm having trouble getting tests to pass on my local machine, but the same 5 fail for me on main and on this branch, so hopefully nothing to fix.

2021-08-06 04:48 UTC, dylans commented
> @dylans done. I'm having trouble getting tests to pass on my local machine, but the same 5 fail for me on main and on this branch, so hopefully nothing to fix.

Ok, we do have one integration test that appears to be legitimately failing now @bkrausz , the test in https://github.com/ianstormtaylor/slate/blob/main/cypress/integration/examples/code-highlighting.ts#L19-L34 

Here's the specific error: ```  1) code highlighting
       highlights javascript syntax:
     AssertionError: Timed out retrying after 4000ms: expected '<span.css-14qid8c>' to contain 'const'
      at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/integration/examples/code-highlighting.ts:124:14)```

Please have a look when you have time.

2021-08-06 23:02 UTC, bkrausz commented
Is it possible that this test is flaky? I'm seeing it working correctly locally, both via test passing and manually checking on a new build. Would you mind triggering a re-run to confirm and/or snagging the video from the test server? I don't have access to either.

2021-08-06 23:15 UTC, bkrausz commented
On further inspection it looks like this PR isn't actually doing what it claims to do anymore...we still get flickering on spellcheck. I'm using it to get other native actions (specifically so horizontal scroll will work so Slate can emulate Input boxes). This PR needs deeper investigation: we are still avoiding calling `preventDefault`, but it seems that's no longer sufficient.

I doubt I'll have time to go that deep on this PR and fix it again, if anyone else is interested in taking this over that would be more than welcome.

2021-08-06 23:18 UTC, lukesmurray commented
If anyone wants to do it you could potentially use git bisect to find the commit where the change broke.

2021-08-06 23:27 UTC, bkrausz commented
FYI this PR does in fact still fix autocorrect support in Safari, just not the spellcheck squiggle blink.

2021-08-06 23:59 UTC, bkrausz commented
Ok, I got nerdsniped enough to bisect this...it's from #4158, which causes every string to rerender. I'm pushing up a revert for it, can someone who knows how to test IME see if the bug described there is also fixed by this one? We may need to add a few extra characters to the [allowlist](https://github.com/ianstormtaylor/slate/pull/3888/commits/6a51623b905bc69e3de6edfc4f88a526224e9905#diff-1d0c52ec4c5562d96965f789988bd4efd4a6d24b88527918987d06bcc43d15adR282), as I don't know what characters it produces.

2021-08-07 00:09 UTC, dylans commented
> Ok, I got nerdsniped enough to bisect this...it's from #4158, which causes every string to rerender. I'm pushing up a revert for it, can someone who knows how to test IME see if the bug described there is also fixed by this one? We may need to add a few extra characters to the [allowlist](https://github.com/ianstormtaylor/slate/pull/3888/commits/6a51623b905bc69e3de6edfc4f88a526224e9905#diff-1d0c52ec4c5562d96965f789988bd4efd4a6d24b88527918987d06bcc43d15adR282), as I don't know what characters it produces.

I know how to test IME. I’ll look at it over the weekend.

2021-08-11 04:48 UTC, dylans approved these changes
Overall this looks good to me @bkrausz... I'm going to let it sit for a couple more days so I can give it another look and in case anyone else wants to take a second look.

2021-08-11 04:50 UTC, brycedewitt commented
Just piping in to check I'm clear on this - this fixes autocorrect on safari but not the squiggles issue?

2021-08-11 08:13 UTC, bkrausz commented
> Just piping in to check I'm clear on this - this fixes autocorrect on safari but not the squiggles issue?

It does...something to improve blinking. With this PR all spellcheck on the line is removed until a space is pressed. This *almost* matches native browsing, which blocks the specific word's spellcheck while it's being edited. I do not know why this is the case.

https://user-images.githubusercontent.com/364070/128993742-f0bfdda2-b3ba-40c7-9b88-e18b3f891ecb.mov

2021-08-11 13:11 UTC, dylans reviewed
minor comments cleanup

2021-08-11 13:11 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +          // and because of the selection moving in `insertText` (create-editor.tx).
```suggestion
          // and because of the selection moving in `insertText` (create-editor.ts).
```

2021-08-11 13:11 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +          // I see this when there is an inline element, like a link, and you select
```suggestion
          // When there is an inline element, e.g. a link, and you select
```

2021-08-11 13:11 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +          // Skip native if there are marks, as that means
```suggestion
          // Skip native if there are marks, as
```

2021-08-11 13:11 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +          // Only do it for single character a-z or space for now.
```suggestion
          // Only use native character insertion for single characters a-z or space for now.
```

2021-08-11 13:11 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +            // to stop rendering, so that browsers functions like autocorrect
```suggestion
            // to stop rendering, so that browser functions like autocorrect
```

2021-08-11 22:57 UTC, merged

2021-08-13 09:14 UTC, githoniel commented
@bkrausz sorry for the bug caused by my hacky PR that drove you crazy😥。

@dylans but this pr did not fix the IME double input when add mark bug. I have test in the main branch with this pr merged like below: 
![xx](https://user-images.githubusercontent.com/17848159/129333216-59fa1995-65f1-47e4-995b-ed6886ca445a.gif)

this anoy bug will cause slate to crash and this is very common used for the peope using IME

I have a new idea to fix this: create an node with place-holder text and move selection to it in advance before composition start, remove the node if there is no text after composition end. I will try to implement later

2021-08-13 10:52 UTC, dylans commented
> @bkrausz sorry for the bug caused by my hacky PR that drove you crazy😥。
> 
> @dylans but this pr did not fix the IME double input when add mark bug. I have test in the main branch with this pr merged like below:
> ![xx](https://user-images.githubusercontent.com/17848159/129333216-59fa1995-65f1-47e4-995b-ed6886ca445a.gif)
> 
> this anoy bug will cause slate to crash when click on the text that should not exist.
> 
> I have a new idea to fix this without force re-render string component. I will try to implement later

ok @githoniel let me know. We've had quite a few IME related contributions lately and it would be great to be done with the double input issue resolved for good.

2021-08-18 11:50 UTC, dylans commented
@bkrausz fyi, this update seems to have caused a regression for code highlighting/decorations, see the notes in #4445.

2021-10-15 22:43 UTC, jaked commented
rather than defer the `insertText` call to the underlying `Editor`, would it make sense to accumulate native operations in `onDOMBeforeInput` and flush them in `onInput` entirely within `Editable`, so `insertText` is not called at all until `onInput`? It seems like a lot of the bugs around this (e.g. #4530, #4541) have to do with interactions with non-default `insertText` implementations.

If this seems like a reasonable idea I can try to do a PR.

2021-12-13 07:02 UTC, juliankrispel commented
Has this worked as part of these prs? I have built commits from both this pr and #4605 and have not found a working version. Pointers appreciated 🙏