Handle sibling moves in moveNodes transform
ianstormtaylor/slate pull request #3978
Opened 2020-11-11 21:48 UTC by BobElDevil

#### Is this adding or improving a _feature_ or fixing a _bug_?
Fixing a bug

#### What's the new behavior?
moveNodes transform properly handles sibling moves when multiple nodes are moved

During application, 'moveNodes' uses path refs to track the nodes that are being moved, as well as the destination path. This relied on the fact that when a node is inserted, the node that was originally at that location is pushed after, so the transform would ensure subsequent moves occur after the previous ones. 

However when a sibling move occurs from an earlier to later index, the node at that location actually shifts earlier. This means when we loop through the move ops, subsequent moves end up being targeted to before the previous ones, reversing the order of the nodes. 

#### How does this change work?

Detect a sibling move, and adjust the destination of the move in the loop when that's the case

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

2020-11-11 21:51 UTC, jason-krypton commented
LGTM. Similar to other bugs that have been fixed with sibling moveNodes.

2020-12-11 17:55 UTC, BobElDevil commented
@BrentFarese tagging you on this one. Thanks for taking a look!

2020-12-30 14:34 UTC, BrentFarese commented on packages/slate/src/transforms/node.ts
> +          toRef.current = Path.next(toRef.current!)
I generally think the use of `!` in Slate core is an anti-pattern.  Can we just move to check that `toRef.current` exists in the if block on line 381?

2020-12-30 14:37 UTC, BrentFarese requested changes
Apart from a minor requested change, this would look good to merge!  Make sure it's up to date w/ Master too please.  Thanks.

2021-01-05 23:51 UTC, BobElDevil commented
@BrentFarese Made the requested changes and rebased on master. Thanks for the review 👍

2021-01-14 22:44 UTC, BrentFarese commented
@BobElDevil I think if you install `@babel/helper-call-delegate` it will fix the deploy?  Give it a crack and then glad to merge.

2021-01-29 19:06 UTC, BobElDevil commented
@BrentFarese Sorry missed the notification for this, just rebased on the latest which pulled in the babel dependency, checks should be passing now.

2021-01-29 19:13 UTC, BrentFarese approved these changes

2021-02-16 17:27 UTC, BrentFarese approved these changes

2021-02-16 17:27 UTC, merged