Fix ios chrome ime double input issue.
ianstormtaylor/slate pull request #4049
Opened 2021-01-19 13:28 UTC by ulion

#### Is this adding or improving a _feature_ or fixing a _bug_?

Fix a bug

#### What's the new behavior?

IME input won't duplicate.

#### How does this change work?

IOS chrome looks just fine, so no need special code on compositionEnd to insertData.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

2021-03-31 22:29 UTC, ianstormtaylor commented
Thanks @ulion!

2021-08-04 12:59 UTC, dylans requested changes

2021-08-04 12:59 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +              if (!IS_SAFARI && !IS_FIREFOX && !IS_IOS && event.data) {
This looks fine, but it's stale as we recently updated it to IS_FIREFOX_LEGACY. Could you do a quick rebase and then we can land this? Thanks @ulion!

2021-08-04 13:46 UTC, ulion commented
rebased

Dylan Schiemann ***@***.***> 于2021年8月4日周三 下午9:00写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In packages/slate-react/src/components/editable.tsx
> <https://github.com/ianstormtaylor/slate/pull/4049#discussion_r682591573>:
>
> > @@ -613,7 +614,7 @@ export const Editable = (props: EditableProps) => {
>                // aren't correct and never fire the "insertFromComposition"
>                // type that we need. So instead, insert whenever a composition
>                // ends since it will already have been committed to the DOM.
> -              if (!IS_SAFARI && !IS_FIREFOX && event.data) {
> +              if (!IS_SAFARI && !IS_FIREFOX && !IS_IOS && event.data) {
>
> This looks fine, but it's stale as we recently updated it to
> IS_FIREFOX_LEGACY. Could you do a quick rebase and then we can land this?
> Thanks @ulion <https://github.com/ulion>!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ianstormtaylor/slate/pull/4049#pullrequestreview-722250389>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABKYHKKPQHZQJPKVYMDSJLT3E2VFANCNFSM4WIYZH5A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-04 18:12 UTC, dylans approved these changes

2021-08-04 18:14 UTC, dylans commented
Thanks @ulion, I'm making a push to land obvious PRs asap, so I hope to get this merged very soon.

2021-08-05 05:23 UTC, dylans commented
@ulion  This one was missing a changeset so I've added a PR on your branch. If you don't mind please accept and push into this PR and then I'll land it.

2021-08-05 11:52 UTC, dylans commented on .changeset/metal-trees-rest.md
> +Fix ios chrome ime double input issue.
```suggestion
fix ios chrome ime double input issue
```

2021-08-05 11:53 UTC, dylans commented on .changeset/metal-trees-rest.md
> +Fix ios chrome ime double input issue.
My fault, I failed to run prettier on the changeset... sigh.

2021-08-05 15:24 UTC, dylans commented on .changeset/metal-trees-rest.md
> +"slate-react": patch
```suggestion
'slate-react': patch
```

2021-08-05 15:24 UTC, dylans commented on .changeset/metal-trees-rest.md
> +"slate": patch
```suggestion
'slate': patch
```

2021-08-06 00:01 UTC, dylans commented
@ulion sorry about the prettier issue, if you can please run `yarn lint:prettier --write` on the PR and push then I can merge. Or just give me edit permission on the PR and I'll fix and merge. Thanks.

2021-08-06 02:18 UTC, ulion commented
> @ulion sorry about the prettier issue, if you can please run `yarn lint:prettier --write` on the PR and push then I can merge. Or just give me edit permission on the PR and I'll fix and merge. Thanks.

done both.

2021-08-06 03:58 UTC, merged