Color picker
ianstormtaylor/slate pull request #4087
Opened 2021-02-20 23:08 UTC by Lavcodes

**Description**
#4076 Adds a Color Picker feature to allow user to choose the color they want to highlight the text with.

**Issue**
Fixes: #4076

**Example**
Overview

![OverView](https://user-images.githubusercontent.com/59924327/108610745-0ce2a700-73fe-11eb-9476-565cc25a03d8.png)

How it opens up

![OpensUp](https://user-images.githubusercontent.com/59924327/108610749-179d3c00-73fe-11eb-8030-c2beb3597324.png)

Highlight Color Changes

![HighlightColorChanges](https://user-images.githubusercontent.com/59924327/108610754-21bf3a80-73fe-11eb-80a8-1460199791f9.png)

Different Color

![DiffColor](https://user-images.githubusercontent.com/59924327/108610761-34397400-73fe-11eb-8d90-f1a695a03daa.png)

**Context**
Adds an additional feature as earlier the highlight color was quite subtle. This allows User to flexibly choose a color of their choice. Usage can be extended into other features, that people making use of slate may want to use in their own projects.

**Checks**
- [ YES ] The new code matches the existing patterns and styles.
- [ YES ] The tests pass with `yarn test`.
- [ YES ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ YES ] The relevant examples still work. (Run examples with `yarn start`.)

2021-08-04 12:56 UTC, dylans requested changes
Overall this would be a nice example to add. Please see my comments... main thing to change is that this really should not be modifying the issue creation templates, etc. as part of this PR.

Also, Plate recently added a font/font-ui plugin into  https://github.com/udecode/plate/tree/main/packages/marks ... if you have interest, your example has a much better UX and I'm sure it would be a welcome contribution there as well.

2021-08-04 12:56 UTC, dylans commented on package.json
> -    "typescript": "3.9.7"
somehow my attempt to rebase this removed TS which is not what was intended.

2021-08-04 12:56 UTC, dylans commented on .github/ISSUE_TEMPLATE/bug-core.md
> +
Could you please update this PR to not be applying formatting changes to the .github templates?

2021-08-19 07:43 UTC, echarles commented on package.json
>      "react-dom": "^16.12.0",
I don't see the `react-pick-color` being used in the code. I may miss something looking at the diff?

2021-08-19 07:44 UTC, echarles commented on package.json
> +    "react-pick-color": "^1.0.1",
I don't see the react-pick-color being used in the code. I may miss something looking at the diff?

2021-09-07 11:54 UTC, dylans commented
I'm closing this one out due to inactivity and the unaddressed feedback. Feel free to either re-open or raise a new PR if you're interested in finishing this addition to the examples. Thanks!

2021-09-07 11:54 UTC, closed without merging