Proposal for Remove useCallback from walkthroughs
ianstormtaylor/slate pull request #4091
Opened 2021-02-23 04:00 UTC by pukingrainbows

I have seen in the walkthrough the use of `useCallback` but I don't think are need it, and add a small complexity while understanding the concept, if we moved out the function outside of the component will be stable and will not require to maintain either referential identity or calculated complex logic. 

If people think this is a good idea I can go and update all documentation to remove unnecessary `useCallback` from the example.

unless I'm missing something.

**Description**
A clear and concise description of what this pull request solves. (Please do not just link to a long issue thread. Instead include a clear description here or your pull request will likely not be reviewed as quickly.)

**Issue**
Fixes: (link to issue)

**Example**
A GIF or video showing the old and new behaviors after this pull request is merged. Or a code sample showing the usage of a new API. (If you don't include this, your pull request will not be reviewed as quickly, because it's much too hard to figure out exactly what is going wrong, and it makes maintenance much harder.)

**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve it the way you did. (This is incredibly helpful so that reviewers don't have to guess your intentions based on the code, and without it your pull request will likely not be reviewed as quickly.)

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)

2021-03-31 21:35 UTC, ianstormtaylor commented
Hey @pukingrainbows that change sounds good to me. Can you use the `const = ` syntax if you make that change everywhere? Thanks!

2021-08-04 12:47 UTC, dylans requested changes

2021-08-04 12:47 UTC, dylans commented on docs/walkthroughs/04-applying-custom-formatting.md
> +function renderElement(props) {
```suggestion
const renderElement = (props) => {
```

2021-08-18 22:44 UTC, dylans approved these changes
As noted in my comment, I'm happy to approve a PR for this. Given the time since this was opened, I'm going to go ahead and land this change and close the PR. We'll accept PRs for any other similar changes in a more timely manner.

2021-08-18 22:59 UTC, merged