respect reverse option in Editor.nodes
ianstormtaylor/slate pull request #4166
Opened 2021-04-03 06:02 UTC by nivekithan

**Description**
As of now `reverse` option in `Editor.nodes` will be ignored if the type of `at` is `Span`, I dont think this is intentional

**Checks**
- [X] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [X] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [X] The relevant examples still work. (Run examples with `yarn start`.)
- [X] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2021-04-03 06:12 UTC, nivekithan commented
With the tests failing it seems that, it is intentional ?

2021-04-07 17:56 UTC, nivekithan commented
[sandbox](https://codesandbox.io/s/slate-reproductions-forked-s26ys?file=/index.js)

- In above sandox  if you open `console` you will see four `text` nodes. 
- Now if you change `reverse` to `true` then you will see `Editor` obj in `console`

If this is expected result then my pr is wrong. 

But I dont think thats the case as you said `reverse` option will just reverse the output nodes it wont return completely new nodes.

After changing code just like in pr, setting `reverse` to `true` will return 4 `text` nodes which will be in reverse order, which I think is expected result.

2021-04-07 23:44 UTC, thesunny commented
Well, completely misread that. Sorry and thanks for the code example! :)

If the test is written incorrectly, please fix the test so that the PR can be merged.

2021-04-08 04:10 UTC, nivekithan commented
NP , I should have added the sandox in pr itself to avoid any confusion.

I did take a look at failing tests, some failing tests seems to have no relation to the code I changed, I should go deeper to figure things out. 

I can do that but as of now, I am having exams so only after the exams are finished I can figure out why tests are failing

2021-08-07 16:54 UTC, dylans requested changes
@nivekithan let us know if you want to continue working on this PR, or if we should close it out.

2021-08-08 04:17 UTC, closed without merging