feat(slate-react): ReactNode previews and ability to customize it.
ianstormtaylor/slate pull request #4183
Opened 2021-04-08 22:07 UTC by xobotyi

**Description**
- Now previews can be any of ReactNode or ReactNodeArray
- Leaf component is fully refactored, no effects used anymore, just
straight render.
- Preview styling moved to `DefaultLeaf` component so users now able to
change it on their need via `Editable.renderLeaf`.
- `Editable` component has proper typing now.

BREAKING CHANGE: anyone using `Editable.renderLeaf` and not calling
`DefaultLeaf` on placeholder leaves wont have placeholder displayed.
Sadly this is the only way to allow placeholder customisation.

**Issue**
Fixes: (link to issue)

**Example**
A GIF or video showing the old and new behaviors after this pull request is merged. Or a code sample showing the usage of a new API. (If you don't include this, your pull request will not be reviewed as quickly, because it's much too hard to figure out exactly what is going wrong, and it makes maintenance much harder.)

**Context**
Previously leaf required `useEffect` since placeholder been absolutely positioned and has unable to stretch parent, relative positioning was impossible du to ability to pu cursor after placeholder.
Now it is way simpler in terms of logic - simple rendering with styles, in terms of markup - now it is 3 spans:
 - _wrapper_ is `inline-block`,  has relative positioning and stretched to full width.
   - _placeholder wrapper_ - also `inline-block` with relative positioning stretched to full width and, so it can stretch thewrapper and change the height of editor.
   - _children wrapper_ - `inline-block` but absolutely positioned and stretched to cover whole parent _wrapper_, threfore there is no ability to click or navigate to the position where cursor id after the placeholder.

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2021-04-08 22:32 UTC, xobotyi commented
Fix: #4182 
Fix: #3608

2021-04-10 06:46 UTC, juliankrispel reviewed
It'll be hard to test this since there are so many changes in this pr. Wouldn't it make sense to split them out?

2021-04-10 10:51 UTC, xobotyi commented
@juliankrispel not sure I'm ready to spend half a day splitting this pr to more granular ones (especially since none of them will make much sence separately).

2021-08-15 12:27 UTC, dylans requested changes
@xobotyi unfortunately this one has also fallen behind main.

If you're still interested in landing this, please update against the latest and then I'll review. Apologies that this PR was allowed to rot.

2021-09-07 11:43 UTC, dylans commented
Closing this one out due to inactivity and it being stale. Feel free to reopen or create a new PR if I missed something here. Thanks!

2021-09-07 11:43 UTC, closed without merging