Fix: IME bug when typing in the inputValue empty
ianstormtaylor/slate pull request #4246
Opened 2021-05-06 11:36 UTC by Janlay884181317

**Description**
When use IME input(such as Chinese, Japanese......) spelling, cursor position will before in placeholder. Now, slate will thorw error.

**Issue**
https://github.com/ianstormtaylor/slate/issues/3882

**Reason**
When use IME input(such as Chinese, Japanese, ......) spelling, cursor position will before in placeholder. So, when inputValue equal empty text, placeholder dom hidden.

**Checks**

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2021-05-06 11:58 UTC, Janlay884181317 commented
![image](https://user-images.githubusercontent.com/36876080/117294621-6eff6400-aea5-11eb-821c-a68418d5b5c2.png)

2021-05-06 12:11 UTC, Janlay884181317 commented
after fix......

![image](https://user-images.githubusercontent.com/36876080/117296095-3c566b00-aea7-11eb-8520-e339002365c3.png)

2021-06-25 18:01 UTC, 7sharp9 commented
When do the patches make it into a release?  This one would be nice to have fixed in a release.

2021-06-25 18:26 UTC, tiberiuichim requested changes
Is it possible not to hardcode the id? We can have multiple slate editors on screen.

2021-06-25 18:30 UTC, Janlay884181317 commented
@7sharp9 @tiberiuichim Ok...... This Pull request hasn't been merged for too long, and I almost forgot about it. Let me see how to deal with hard-coded issues. thanks

2021-08-04 12:04 UTC, dylans approved these changes

2021-08-04 12:05 UTC, dylans requested changes
Actually yes, let's not hardcode the id's please.

2021-09-07 11:45 UTC, dylans commented
@Janlay884181317 are you still interested in addressing this one? Note we have fixed several IME issues recently so you'll want to rebase against main and proceed from there. Thanks!

2021-09-27 16:07 UTC, dylans commented
Closing due to inactivity and due to several other IME fixes possibly making this a situation of already fixed elsewhere. Feel free to reopen or create a clean PR if there's still an issue.

2021-09-27 16:07 UTC, closed without merging