Check minHeight before overriding with placeholder height
ianstormtaylor/slate pull request #4339
Opened 2021-06-15 19:45 UTC by gfohl

**Description**
Currently `leaf.tsx` overides any minHeight styles added to `Editable` via the styles prop with a height of the placeholder.

I added a check to see if the minHeight already has a value before using the placeholder height.

**Issue**
Fixes: 
https://github.com/ianstormtaylor/slate/issues/4233
https://github.com/ianstormtaylor/slate/issues/4314

**Example**
Before with `<Editable style={{ minHeight = 500 }} ...`
![image](https://user-images.githubusercontent.com/67913063/122113798-2f9f2e00-cde8-11eb-8e5f-d0c7ea96a213.png)

After with  `<Editable style={{ minHeight = 500 }} ...`
![image](https://user-images.githubusercontent.com/67913063/122113947-59f0eb80-cde8-11eb-858d-2fe5a5ccdc32.png)

**Checks**
- [X] The new code matches the existing patterns and styles.
- [X] The tests pass with `yarn test`.
- [X] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [X] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2021-06-15 20:29 UTC, gfohl commented
Looks like using classNames and a stylesheet wont work with this unless `!important` is used.  Setting the minHeight for the placeholder is problematic, will work on a better solution

2021-08-13 11:41 UTC, dylans requested changes
@gfohl let us know if you're still interested in working on a solution for this or if we should close this PR. Thanks!

2021-08-21 00:31 UTC, gfohl commented
I still plan on working on a better solution, this currently is at least an improvement, if we can keep it open a bit longer I should have time soon, thanks!

2022-03-07 23:31 UTC, dylans commented
@gfohl still interested in addressing this one?

2022-07-22 23:32 UTC, dylans commented
Closing due to inactivity. Please re-open if there's interest. Thanks.

2022-07-22 23:32 UTC, closed without merging