Capture element selections through useSelected
ianstormtaylor/slate pull request #4365
Opened 2021-07-06 09:58 UTC by samarsault

**Description**
Element selections were not captured by the `useSelected` hook

**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4338

**Example (Before)**

Borrowed from https://github.com/ianstormtaylor/slate/issues/4338.
Code - https://jsfiddle.net/4c21gd5v/22/

![before-selection](https://user-images.githubusercontent.com/451488/121966244-213b0e80-cd23-11eb-94f4-5c0f998c0767.gif)

**Example (After)**

![after-selection](https://user-images.githubusercontent.com/2987087/124580358-a79fc780-de6d-11eb-8831-a2166a874559.gif)

**Context**
From the [code](https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/element.tsx#L134-L139), It seems like the Element does not have access to the SelectedContext, but all elements inside it do. So instead of inside the Element, I wrapped the SelectionContext around the element as following:

```jsx
<SelectedContext.Provider value={!!sel}>
  <ElementComponent
      ...
  />
</SelectedContext.Provider>
```

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2021-07-06 14:55 UTC, cboppert approved these changes
Looks good to me, will leave up to @brentfarese or @timbuckley for a final approval

2021-07-15 15:05 UTC, timbuckley approved these changes

2021-08-06 13:25 UTC, dylans requested changes
Apologies @samarsault , there's a merge conflict from a PR we landed yesterday. Could you please rebase when you have a moment. Also if you could create a changeset (see the comment in the PR) then I'll go ahead and merge into main. Thanks!

2021-08-12 14:03 UTC, dylans approved these changes

2021-08-12 14:03 UTC, merged