fix: insert new node in advance to avoid ime double input with editor marks
ianstormtaylor/slate pull request #4451
Opened 2021-08-13 10:58 UTC by githoniel

**Description**

When the user enters text using the input method, the browser will trigger `composition` event sequentially and insert  composition text in the DOM. At the end of composition, the browser will remove the previously inserted composition text and insert the final IME output text.

But the problem is, if we type with editor mark, slate will create a new node and insert the final text into the new node, which will cause the position of the inserted final text is different from the position of the the previously inserted composition text, which will cause the browser can't remove the previously inserted composition text correctly, and React can't detect the change too.

This will result in inconsistent data structure and DOM rendering and slate will crash when select text that shouldn't exist

**Issue**

Fixes:  #4158

**Example**

![xx](https://user-images.githubusercontent.com/17848159/129345780-c064b760-2bcf-44fa-b6be-3088e0fd958f.gif)

**Context**

I used to force refresh all relevant string component to let `React` correct the wrong DOM node, but it led to more problems, such as the bug mentioned in [Issue] (https://github.com/ianstormtaylor/slate/pull/4158#issuecomment-886820923) that could not trigger the click event and this is hacky and looks stupid

Now I have a new way to implement it.  In `onCompositionStart`  event, we will move selection and insert a new node with mark in advance of `Editor.insertText`. To avoid nodes being deleted by `normalize` due to empty text, I set Text to '\uFEFF'  which will not be displayed in browser and remove it in `onCompositionEnd`  event, and in order to avoid unnecessary removal operations,  a new state `state.hasInsertPrefixInCompositon`  has been added.

**Checks**
- [X] The new code matches the existing patterns and styles.
- [X] The tests pass with `yarn test`.
- [X The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [X] The relevant examples still work. (Run examples with `yarn start`.)
- [X] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2021-08-13 11:53 UTC, dylans reviewed
🎉 Thanks @githoniel , I'll review this over the weekend.

2021-08-13 14:32 UTC, dylans commented
@githoniel any thoughts on whether this might also resolve #3162?

2021-08-14 06:55 UTC, githoniel commented
@dylans no  #3162 exist even without IME

just go example https://www.slatejs.org/examples/search-highlighting

1. input editable in search input
2. input anything after editable highlight

I used to skip this problem in my own editor by  disable highlight when any editor value change when I using decorator a half year ago

2021-08-15 12:16 UTC, dylans requested changes
minor suggestions, then I think we can land this. Thanks @githoniel

2021-08-15 12:16 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +                  } else {
I think in general the Slate preference would be to add a return statement inside the preceding if block rather than using an else.

2021-08-15 12:16 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +                    // and add prefix text to avoid this node removed by normalize
```suggestion
                    // add Unicode BOM prefix to avoid normalize removing this node
```

2021-08-15 12:16 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +                      // remove prefix added in onCompositionStart
```suggestion
                      // remove Unicode BOM prefix added in `onCompositionStart`
```

2021-08-16 11:42 UTC, dylans approved these changes

2021-08-16 11:42 UTC, merged

2021-08-23 13:16 UTC, Jokcy commented
Greate job, a nice solution which I never thought 👍