Fix(editable component): reselect the range created by triple click
ianstormtaylor/slate pull request #4455
Opened 2021-08-16 10:03 UTC by bytrangle

**Description**
When triple clicking inside the editable component of Slate, it doesn't select the correct block. This poses two problems when Slate is to be used as a rich text editor:
- Give false visual feedback, e.g. the wrong toolbar button will be highlighted which leads to confusion
- Unable to apply new style to the selected block only.

This PR tries to select the correct block that users triple click on.

**Issue**
Fixes #4329 

**Example**

Before the fix:

![triple-click-before](https://user-images.githubusercontent.com/28924121/129546926-7fd38c6a-7468-44b4-8303-7f9a08d636af.png)

After the fix:

![triple-click-after](https://user-images.githubusercontent.com/28924121/129546960-a2ecb914-4919-48c6-8a28-97dff9a51976.png)

**Context**

Given a node at path [1].

```js
const editor = {
  children: [
    { // first node
    }
    {
      type: 'paragraph', // the node that receives triple click
      children: [
        { text: "Since it's rich text, you can do things like turn a selection of text " }, // path: [1, 0]
        { text: "bold", bold: true }, // path: [1, 1]
        { text: ", or add a semantically rendered block quote in the middle of the page, like this:" // path: [1, 2]
      ]
    }
  ]
}
```
Suppose we triple click just before the letter "S" of the paragraph.

- Inside the `onClick` event check if there is triple click with `event.detail === 3`.
- By design, the node that users click on will be the text node at path [1, 0]. Call `Editor.above()` to retrieve the closest element ancestor of that text node.
- If the element exists, get all the children of the element. Create an array of their respective path. It should be
[[1, 0], [1, 1], [1, 2]]
- Create a range whose anchor is the first child and focus is the third child. Its anchor offset is 0 (because the selection starts from the very start of the block) and focus offset is the end point of the third child (82) in this case.
- Calling `Transforms.select(range)` to select that range.

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2021-08-16 11:39 UTC, dylans requested changes
Thanks, this change seems reasonable to me. I've made a few minor suggestions.

2021-08-16 11:39 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +                  const elem = Editor.above(editor, {
Might be clearer if it was `const block` rather than `const elem`, since it's not returning a match if it's not a block?

2021-08-16 11:39 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +                    // Get all the children of the element above
```suggestion
                    // Get all the children of the block element above the selection
```

2021-08-16 11:39 UTC, dylans commented on packages/slate-react/src/components/editable.tsx
> +                    // Loop through the generator of element children and create a list of their respective paths.
Please run the linter on this file, this comment and a few below likely exceed the line length rules.

2021-08-16 12:58 UTC, bytrangle commented
> Thanks, this change seems reasonable to me. I've made a few minor suggestions.

Thank you, I will fix them tomorrow.

But I've noticed that when I triple click on the second paragraph of the **Rich Text** example, the Quote Block button is highlighted for a split second and then it's not highlighted.

I think it's because the `useLayoutEffect` is synchronous and run before the `onClick` event handler. The former will try to find the selected DOM range (incorrectly), which makes the Quote Block highlighted, then the `onClick` event handler kicks in.

Do you experience the same?

2021-08-17 09:59 UTC, bytrangle commented
Hello @dylans ,
I've discovered that when I triple click on a block, the `Editor.nodes()` method is supposed to grab a generator of nodes at the current selection, but somehow it always includes the node below the clicked node.

![next-sibling-node-selected-when-triple-click](https://user-images.githubusercontent.com/28924121/129702193-ba94b1a8-4aa4-4d56-afa9-7733ace77600.png)

I've traced the problem down to Slate's [`transform` operator](https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/transforms/general.ts#L318).

This is what happens on the third click:

![third-click-transform](https://user-images.githubusercontent.com/28924121/129704933-919c50c2-9d0b-4fd6-80ce-a3af1852ef5f.png)

Between `createDraft` and `finishDraft`, the `selection` object has been reassigned:

```
transform(editor, op): {
  // ...
  let selection = editor.selection && createDraft(editor.selection)
  try {
    selection = applyToDraft(editor, selection, op)
  } finally {
      editor.children = finishDraft(editor.children)
      if (selection) {
        editor.selection = isDraft(selection)
          ? (finishDraft(selection) as Range)
          : selection
    }
  }
}
```
I think the culprit is probably the helper function `applyToDraft()`, so please allow me a few more days to figure it out.

2021-08-17 14:34 UTC, dylans commented
@bytrangle thanks, I appreciate you digging into this further.

2021-08-24 01:53 UTC, xenostar commented
Just wanted to chime in and say I had some time to test this fix today and it is looking really good. This problem has been plaguing Slate for along time and I'm really looking forward to this fix!

2021-08-24 20:09 UTC, xenostar commented on packages/slate-react/src/components/editable.tsx
> +                if (event.detail === 3) {
Have you thought about setting this to `event.detail >= 3` instead? I noticed when trying a similar approach to this fix locally that if you spam click many times, `event.detail` continues to increment so this wouldn't be fired once you go past 3 clicks.

2021-08-25 11:59 UTC, dylans commented
@bytrangle to clarify, is this really only an issue in Chrome/Chromium-based browsers? I ask as it is a very different PR from your original. Thanks!

2021-08-28 12:02 UTC, dylans commented
> @dylans Thank you, and actually that's a good call because I've written an e2e test for this triple-click behavior.
> 
> It passed, but it opened up a torrent of Typescript warnings. I've tried to fix it as I can, but since I've never used Typescript and just learn as I go, please take a look and tell me what you think.

Your TS seems reasonable. Maybe there are ways to make it less messy, but I think it's fine. Landing this now.

2021-08-28 12:02 UTC, merged

2021-09-06 19:21 UTC, dylans commented
@bytrangle This appears to have caused a regression in Chrome... when you triple check on a link with marks (e.g. bold or italic) and press the backspace/delete key, it only deletes back to the point of the most recent mark.

The example in examples/richtext , triple click on the first line and press backspace to reproduce.

2021-09-08 00:15 UTC, TheSpyder commented
Looking at the stack trace generated by #4490 the use of `!` on values that might be null is to blame. I haven't been paying enough attention to PRs, sorry, I would've flagged that as a concern.

2021-09-08 09:24 UTC, bytrangle commented
@dylans  You mean this?

https://user-images.githubusercontent.com/28924121/132483273-c2630240-1b14-43a8-aab1-750fac7edc10.mp4