Adding update on library import to avoid error message
ianstormtaylor/slate pull request #4688
Opened 2021-11-24 22:05 UTC by YoannBuzenet

The error message ' The package "emotion" has been replaced by "@emotion/styled" ' appears with the old one. With this, it compiles successfully and shows no errors (I'm on next js12).

Great lib, thanks!

**Description**
error message pops when copying the code from [richtext ](https://github.com/ianstormtaylor/slate/blob/main/site/examples/richtext.tsx)example page.

**Issue**
Fixes: update the import on emotion library

**Context**
I'm on nextjs 12, I don't know if it matters.

Thanks for your work, I hope I'll really help later

2021-11-24 22:58 UTC, dylans approved these changes

2021-11-25 17:34 UTC, YoannBuzenet commented
Did it miss because of missing types ? I did it without typescript.

I could have a look at which types it needs ?

2021-12-04 16:08 UTC, dylans requested changes

2021-12-04 16:08 UTC, dylans commented on site/components.tsx
> +import { css, cx } from "@emotion/css";
```suggestion
import { css, cx } from @emotion/css';
```

I think it was failing because the change violated prettier's rules.

2021-12-05 21:26 UTC, dylans commented on site/components.tsx
> +import { css, cx } from @emotion/css';
```suggestion
import { css, cx } from '@emotion/css';
```

2021-12-05 21:29 UTC, dylans requested changes
This is likely failing because it's missing an update to the dependency in package.json and yarn. Please fix and update with a complete PR and then I'll review it. Thanks!

2022-01-11 14:17 UTC, dylans commented
Superseded by #4783

2022-01-11 14:17 UTC, closed without merging