feat: add custom compare node props
ianstormtaylor/slate pull request #4889
Opened 2022-03-13 07:53 UTC by zhugexinxin

**Description**
add custom compare node props

**Example**
node = { type: 'p', attributes: { hidden: true } }

**Context**
If you don't do it, you may create an infinite loop when setting properties

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2022-03-13 11:39 UTC, dylans requested changes
Hi @zhugexinxin could you please add a test showing what is failing currently that passes after this PR lands? Thanks!

2022-03-13 12:44 UTC, zhugexinxin commented
> Hi @zhugexinxin could you please add a test showing what is failing currently that passes after this PR lands? Thanks!

I'm not very good at testing, but I'm willing to try.
For the infinite loop test, I don't know how to write it, maybe I have to understand the jest api

2022-03-13 16:30 UTC, zhugexinxin commented
dev test:integration success
![image](https://user-images.githubusercontent.com/42615243/158069295-974ee3ac-722c-4dba-9bad-adb1e24d18da.png)

I don't know why ci/test:integration fail

2022-03-13 23:58 UTC, zhugexinxin commented
> dev test:integration success ![image](https://user-images.githubusercontent.com/42615243/158069295-974ee3ac-722c-4dba-9bad-adb1e24d18da.png)
> 
> I don't know why ci/test:integration fail

I'll fix this when I have time

2022-03-14 00:18 UTC, zhugexinxin commented
I seem to be missing something, I'll fix this when I have time

2022-03-14 10:14 UTC, zhugexinxin commented
tests have been added

2022-03-14 23:21 UTC, dylans approved these changes

2022-03-14 23:21 UTC, merged

2022-03-15 03:37 UTC, zhugexinxin commented
test:integration fail, but it succeeded on the local machine.
I really need this new version, what help do I need.

![image](https://user-images.githubusercontent.com/42615243/158301039-21d86f9e-2747-46cb-8ea0-4c1b3e2e1b84.png)

2022-03-15 05:12 UTC, dylans commented
> @dylans test:integration fail, but it succeeded on the local machine. I really need this new version, what help do I need.
> 
> ![image](https://user-images.githubusercontent.com/42615243/158301039-21d86f9e-2747-46cb-8ea0-4c1b3e2e1b84.png)

Integration tests are somewhat flaky on GitHub Actions and timeout prematurely. I'll push an updated release now.

2022-03-15 09:40 UTC, zhugexinxin commented
> > @dylans test:integration fail, but it succeeded on the local machine. I really need this new version, what help do I need.
> > ![image](https://user-images.githubusercontent.com/42615243/158301039-21d86f9e-2747-46cb-8ea0-4c1b3e2e1b84.png)
> 
> Integration tests are somewhat flaky on GitHub Actions and timeout prematurely. I'll push an updated release now.

thanks

2022-03-16 11:14 UTC, BitPhinix commented
I'm not sure I get why `compare` is needed here. I don't really get the problem it solves. Couldn't the normalizeNode simply be written in a slightly different way?