Call `scrollSelectionIntoView()` more often
ianstormtaylor/slate pull request #4996
Opened 2022-05-17 14:26 UTC by e1himself

**Description**
Trigger `scrollSelectionIntoView` when cursor moves between text lines.

**Issue**
Fixes: #4995

**Example**

The custom `scrollSelectionIntoView` function is now called when the cursor is moved between paragraph text lines.

Before:

https://user-images.githubusercontent.com/370680/168827772-648b0317-a5a9-4dae-8f82-edfcd9851da1.mp4

After:

https://user-images.githubusercontent.com/370680/168835027-bcc09f4f-0323-47e9-a986-0dde3f565e06.mp4

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2022-05-17 21:33 UTC, dylans approved these changes

2022-05-17 22:01 UTC, BitPhinix commented
`scrollSelectionIntoView` causes a reflow so this might have unexpected performance implications, especially on long documents

2022-05-17 22:20 UTC, BitPhinix commented
Just confirmed it - it seems to add about 10ms to every keystroke when typing at the bottom of larger docs and is definitely noticeable.

<img width="507" alt="Screenshot 2022-05-17 at 18 16 45" src="https://user-images.githubusercontent.com/13185548/168921655-3ffcdf10-23b1-45a8-84bc-1f57d8158836.png">

I don't think we should take over the default browser behavior here. If desired the `scrollIntoView` call can be added very easily in user-land.

2022-05-17 23:23 UTC, dylans requested changes
Per the performance note from @BitPhinix we probably shouldn't land this as-is.

2022-05-18 08:35 UTC, e1himself commented
@BitPhinix @dylans 

Thank you for looking into this. I appreciate the quick response :+1: 

I'll do more research on it. But meanwhile, I'm closing this PR. Thanks!

2022-05-18 08:35 UTC, closed without merging