Change how Slate context works and introduce `useSlateSelection` hook
ianstormtaylor/slate pull request #5041
Opened 2022-07-06 12:20 UTC by bryanph

**Description**
This changes how `SlateContext` gets updated. This used to be done by replacing the context with a fresh array every time. This change uses an incrementing counter instead. This makes the code easier to read and has the added benefit of using the version counter to perform some logic such as not updating. I was drafting a solution to make DOM selection syncing more reliable in https://github.com/ianstormtaylor/slate/pull/5017 using this capability but it needs more work which is why I'm opening this PR instead for now.

This also introduces a `useSlateSelection` hook which you can use to get the latest slate selection (only triggers when it's actually updated).

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2022-07-15 13:15 UTC, dylans requested changes
I like this. It would be good to hear from anyone else before we land it. Also thinking this should be minor rather than patch?

2022-07-15 14:40 UTC, bryanph commented
@dylans I was thinking no breaking stuff, so just a patch. But adding the hooks might make it a minor?

2022-07-15 22:21 UTC, dylans commented
> @dylans I was thinking no breaking stuff, so just a patch. But adding the hooks might make it a minor?

Exactly, generally when new things are added it should be minor imo. Thanks!

2022-07-16 12:22 UTC, dylans approved these changes

2022-07-22 23:27 UTC, merged