Add normalizeSelection api to editor
ianstormtaylor/slate pull request #5090
Opened 2022-08-19 12:03 UTC by yanmao-cc

**Description**
In the case of selecting some cells on the table, I want any node's change operation to be applied separately using the selection in each cell

table selection effect on example
![image](https://user-images.githubusercontent.com/55792257/185611280-679c18c5-c054-4494-8ca1-33ee1b408d69.png)

I'm trying to implement rich text without using the contenteditable property(https://github.com/editablejs/editable).
This is the result after selecting the table

![image](https://user-images.githubusercontent.com/55792257/185611586-8171747e-7d74-4a45-903e-e12a55d73852.png)

In fact, this does not change the selection, cell3 is still selected, but I want to reorganize the selection by adding the normalizeSelection api

**Example**
![20220819194658](https://user-images.githubusercontent.com/55792257/185611912-318c2aeb-1769-4d78-af9a-255a79dfb386.gif)

**Context**
Traversing the cells that need to be changed in the table plugin
```
const { normalizeSelection } = editor
editor.normalizeSelection = (fn) => {
  if (isTable) {
   const { selection } = editor
   for(const cell of cells) {
     fn(...cell selection)
   }
  // restore selection
  Transforms.select(editor,  selection)
  } else {
    normalizeSelection(fn)
  }
}
```
Call the normalizeSelection method within withoutNormalizing and modify the editor's selection property
```
withoutNormalizing(editor: Editor, fn: () => void): void {
    const value = Editor.isNormalizing(editor)
    Editor.setNormalizing(editor, false)
    try {
      editor.normalizeSelection(selection => {
        if (editor.selection !== selection) editor.selection = selection
        fn()
      })
    } finally {
      Editor.setNormalizing(editor, value)
    }
    Editor.normalize(editor)
  }
```

If you agree with this approach, I will improve the follow-up work and documentation

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2022-08-22 23:51 UTC, dylans requested changes
This generally looks fine. I would want to see a few additional things before landing it:

* Unit test(s)
* Update to docs
* Changeset (see instructions in the PR)

2022-08-23 09:42 UTC, yanmao-cc commented
> I'm not a fan of this change tbh, as this can be archived in other ways and seems quite hackish (running stuff passed into `withoutNormalizing` multiple times is quite unexpected and will break a tone of stuff, even within slate itself). This also changes the signature/behavior of `Editor.marks` when not using `normalizeSelection` (it will never return null and always a new object, so you can't memo anything based upon it). It also changes the editor selection without using operations which will cause other unintended side-effects.
> 
> Even ignoring that, it's very counterintuitive what `normalizeSelection` does, even with the documentation (at least for me). This should be handled outside of slate and can be done in user-land, even though it's a bit more complex.

Yes, I'm currently working on it outside the slate. But if you have a data type like `grid`, it seems to be a must

```javascript
Editor.withoutNormalizing = (editor: Editor, fn: () => void) => { 
  if(Editable.isEditor(editor)) {
    editor.normalizeSelection(selection => {
      if(editor.selection !== selection) editor.selection = selection
      withoutNormalizing(editor, fn)
    })
  } else {
    withoutNormalizing(editor, fn)
  }
}

Editor.marks = (editor: Editor): Omit<Text, 'text' | 'composition'> => {
  let marks: Omit<Text, 'text' | 'composition'> = {}
  if(Editable.isEditor(editor)) {
    editor.normalizeSelection(selection => {
      const editorMarks = slateMarks({...editor, selection})
      marks = Object.assign(marks, editorMarks)
    })
  } else {
    return slateMarks(editor) ?? marks
  }
  return marks
}
```

2022-08-23 09:59 UTC, BitPhinix commented
The way we handle it inside our plugins is that we added an `editor.toggleMark` inside our "core plugin" which is used by keyboard shortcuts etc. to toggle marks. We intercept this `toggleMark` inside our table plugin to handle it based upon the "table selection". You can use a similar pattern for almost everything else without changing anything about `Editor.withoutNormalizing`/`Editor.marks`

2022-08-23 10:29 UTC, yanmao-cc commented
> The way we handle it inside our plugins is that we added an `editor.toggleMark` inside our "core plugin" which is used by keyboard shortcuts etc. to toggle marks. We intercept this `toggleMark` inside our table plugin to handle it based upon the "table selection". You can use a similar pattern for almost everything else without changing anything about `Editor.withoutNormalizing`/`Editor.marks`

This is possible in an ideal situation. But I have here not only toggleMark but also toggleList , toggleQuoteblock , toggleHeading and so on. And other plugins also use a lot of APIs such as setNodes wrapNodes unwrapNodes.

So I abstract things like tables into grid data types. Ideally, other non-grid plugins do not need to pay attention to whether they are in the grid. Each grid plugin will handle the selection and boundary by itself and pass it on.

2022-08-23 10:39 UTC, BitPhinix commented
I'm sorry, but again, I don't think this is something that should be handled inside slate itself. This is something you should handle inside your editor. You could add something similar to what you do to the `withoutNormalizing` in this pr. E.g., adding a `Editor.modifySelection(fn: (range: Range) => void)` inside your editor which is then called with the ranges you would get with your current `normalizeSelection` call (just thinking out loud, not sure about your exact implementation). But you can't assume that everything that is passed to `withoutNormalizing` can just be called again with a different selection because that would be a huge breaking change for almost all code bases using slate (and would probably break a tone of stuff inside slate internally).

2022-08-23 11:21 UTC, yanmao-cc commented
> I'm sorry, but again, I don't think this is something that should be handled inside slate itself. This is something you should handle inside your editor. You could add something similar to what you do to the `withoutNormalizing` in this pr. E.g., adding a `editor.modifySelection(fn: (range: Range) => void)` inside your editor which is then called with the ranges you would get with your current `normalizeSelection` call (just thinking out loud, not sure about your exact implementation). But you can't assume that everything that is passed to `withoutNormalizing` can just be called again with a different selection because that would be a huge breaking change for almost all code bases using slate (and would probably break a tone of stuff inside slate internally).

It doesn't matter, I just submitted this PR tentatively, it may be more of a discussion process. Because I really need a way to modify `selection` before executing api calls such as `setNodes` `wrapNodes` `unwrapNodes`. From the perspective of the currently provided API, `withoutNormalizing` is a good entry point

2022-08-26 08:35 UTC, closed without merging