Use callback-style ref in `Element` component
ianstormtaylor/slate pull request #5105
Opened 2022-08-31 06:00 UTC by yume-chan

**Description**
When a parent Element re-render child Elements using React context, Slate can no longer track the DOM node to Slate node mapping.

**Issue**
Fixes #5104

**Example**
The same repro in #5104 with locally patched `slate-react` package:

https://user-images.githubusercontent.com/1330321/187604574-36b4e2ea-2616-42fe-a51e-73de17498563.mp4

**Context**
This PR changes `Element` to use callback-style ref, so every change in the ref target (including unmounting) will be observed.

`Editor` and `Leaf` doesn't need this treatment, because they attach `ref` to nodes that can only change when the component itself re-renders.

However, if we also change `Editor` and `Leaf`, then `ELEMENT_TO_NODE` and `NODE_TO_ELEMENT` maps can use normal `Map`s, instead of `WeakMap`s, which is 5x faster in reading, according to some random [benchmark](https://gist.github.com/jung-kim/d146b25ea754e73bf60a?permalink_comment_id=3811484#gistcomment-3811484).

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2022-08-31 21:14 UTC, dylans requested changes
I'm verifying that this won't break in some other way.

In the interim, please follow the instructions in the PR and add a changeset so that this ready to go once I've had time to review/verify.

2022-09-01 11:05 UTC, yume-chan commented
Changset added.

2022-09-01 12:49 UTC, dylans approved these changes

2022-09-02 09:57 UTC, bryanph approved these changes
Great change 👍

2022-09-06 04:15 UTC, merged