fix: error getting parentEntry in selection range
ianstormtaylor/slate pull request #5168
Opened 2022-10-26 12:46 UTC by i-artist

**Description**
Wrong matching ancestor above a location in the document when selection range multiple nodes.

**Jsfiddle**
[demo](https://jsfiddle.net/Steven_zhong/wsoaL4zk/45/)

**Context**
The correctness of the method is guaranteed by different verification processing logic for points, paths or range.

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2022-10-26 23:35 UTC, dylans requested changes
Ideally I'd like to see a test added that fails before this change and passes afterwards to avoid a future regression.

2022-10-27 03:42 UTC, i-artist commented
> Ideally I'd like to see a test added that fails before this change and passes afterwards to avoid a future regression.

Yeah, I agree with you.

2022-10-27 03:54 UTC, i-artist commented
before change:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/29483801/198187248-568dacb8-1532-4936-b9cd-69e6bfe65e51.png">

after change:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/29483801/198187382-5030fd7f-ef2d-4c94-9bb6-9b11b234a4d7.png">

2022-10-28 15:38 UTC, dylans approved these changes
Thanks!

could you add a quick changeset too and then I’ll land this over the weekend? (There’s instructions in the PR)

2022-10-29 07:36 UTC, i-artist commented
> Thanks!
> 
> could you add a quick changeset too and then I’ll land this over the weekend? (There’s instructions in the PR)

Sure, I'll add it later.

2022-11-08 12:37 UTC, merged