feat: allow to change clipboard fragment format name
ianstormtaylor/slate pull request #5267
Opened 2023-01-23 18:07 UTC by ilya2204

**Description**
Allow customization of clipboard fragment format name. Based on #5233 and [slate-angular](https://github.com/worktile/slate-angular/blob/master/packages/src/plugins/with-angular.ts#L22)

**Issue**
#5233

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2023-01-26 12:06 UTC, dylans approved these changes

2023-01-26 12:06 UTC, dylans requested changes
Thanks @ilya2204 ! Could you please add a changeset and then I'll land this?

2023-01-30 16:08 UTC, ilya2204 commented
@dylans I added changeset)

2023-02-01 11:44 UTC, dylans commented
For some reason this is failing our integration tests. I'm going to try to run it again later today.

2023-02-09 18:50 UTC, dylans commented
@ilya2204 yes, we landed a PR a couple of days ago which fixed the failing tests. Thanks for reminding me!

2023-02-09 18:50 UTC, merged