Add unit:offset tests.
ianstormtaylor/slate pull request #5269
Opened 2023-01-23 20:11 UTC by boweiliu

**Description**
A clear and concise description of what this pull request solves. (Please do not just link to a long issue thread. Instead include a clear description here or your pull request will likely not be reviewed as quickly.)

**Issue**
Fixes: (link to issue)

**Example**
A GIF or video showing the old and new behaviors after this pull request is merged. Or a code sample showing the usage of a new API. (If you don't include this, your pull request will not be reviewed as quickly, because it's much too hard to figure out exactly what is going wrong, and it makes maintenance much harder.)

**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve it the way you did. (This is incredibly helpful so that reviewers don't have to guess your intentions based on the code, and without it your pull request will likely not be reviewed as quickly.)

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2023-01-25 01:33 UTC, boweiliu commented
@dylans could i get some help running the workflows?

2023-01-26 12:10 UTC, dylans requested changes
@boweiliu Thanks, always appreciate good quality tests getting added! It looks like you just need to run Prettier on your PR and then we should be ready to land it.

2023-02-22 11:55 UTC, dylans commented
@boweiliu A reminder of my previous note:

Thanks, always appreciate good quality tests getting added! It looks like you just need to run Prettier on your PR and then we should be ready to land it.

2023-12-16 11:40 UTC, dylans commented
@boweiliu quick reminder, run prettier on this and then we can land it.

2024-08-20 23:20 UTC, dylans approved these changes

2025-05-05 15:34 UTC, dylans commented
This is now very stale unfortunately. We can revisit in a new PR if still relevant.

2025-05-05 15:34 UTC, closed without merging