Punctuation Mark "+" Support Added
ianstormtaylor/slate pull request #5316
Opened 2023-02-25 19:05 UTC by GeneralChauhan

I just added the support for "+" punctuation mark.

Fixes: https://github.com/ianstormtaylor/slate/issues/5255

2023-02-27 00:29 UTC, dylans requested changes
Looks fine. Please add a changeset per the instructions so that this shows up in the release notes. Thanks!

2023-05-08 18:34 UTC, GeneralChauhan commented
What is a changeset? I'm new to this repo and open source as well.

2023-06-07 06:21 UTC, kanapka94 commented
https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md

2023-12-16 11:38 UTC, dylans approved these changes

2023-12-16 11:41 UTC, merged