Fixed large Margin
ianstormtaylor/slate pull request #5468
Opened 2023-06-25 17:54 UTC by Noothan-am

**Description**
solves large space when we press Enter 

**Issue**
Fixes: #5457 

*ScreenShot*
![image](https://github.com/ianstormtaylor/slate/assets/100135382/416a51ed-9d3d-41f9-b4ad-86f05d276701)

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

2023-06-28 15:32 UTC, dylans requested changes
I think a better approach for this and a few other things would be to make them configurable, or provide documentation to make it clear how to override them.

Not sure why this edit removed spaces in CSS and a commented out value isn't really a final solution.

2023-06-28 16:43 UTC, Noothan-am commented
> I think a better approach for this and a few other things would be to make them configurable, or provide documentation to make it clear how to override them.
> 
> Not sure why this edit removed spaces in CSS and a commented out value isn't really a final solution.

Hey @dylans, when we click enter, the margin used to get added, so I wanted to remove that space by commenting out the CSS responsible for this issue `margin-top: 1em`. The spaces in the CSS code are because of my code formatter that is not the actual change I made. I have only changed the margin-top by commenting it out. Should I remove this comment and add the feature discussed earlier?

2023-08-05 13:58 UTC, dylans commented
ok, I can land this once a changeset gets added and the linting issue are resolved.

2023-10-03 00:49 UTC, ApplyBoardDak commented on site/public/index.css
> +:not(pre)>code {
why this change?

2023-10-03 00:49 UTC, ApplyBoardDak commented on site/public/index.css
> +[data-slate-editor]>*+* {
same question here

2023-10-04 13:10 UTC, dylans commented
@Noothan-am do you have plans to address the feedback or should I close this PR?

2025-05-05 15:36 UTC, dylans commented
This is now very stale unfortunately. We can revisit in a new PR if still relevant.

2025-05-05 15:36 UTC, closed without merging