Fix firefox disconnected selection api usage
ianstormtaylor/slate pull request #5486
Opened 2023-07-25 16:40 UTC by WcaleNieWolny

**Description**
This PR fixes the invalid usage of the selection API in firefox. Firefox allows disconnected ranges that cause problems with slate. I originally started to work on this to fix . [this issue](https://github.com/udecode/plate/issues/560)

**Issue**
Fixes: (I do not think this fixes any slate issue, however I am not sure. I did not checked)

**Example**
Before my changes:

https://github.com/ianstormtaylor/slate/assets/50914789/54a02c0a-4211-4d87-b5bc-197433eafd62

After my changes:

https://github.com/ianstormtaylor/slate/assets/50914789/84c69ec1-3088-480f-a75e-7e73ab93bab7

**Context**
1:\
`anchorNode`, `anchorOffset`, `focusOffset`. Do not behave the same in chrome and in firefox. In firefox if there is more then 1 range said values would be invalid. I fixed this by using the `getRangeAt` function (see `toSlateRange` changes).
2:\
I reversed [this pr](https://github.com/ianstormtaylor/slate/pull/5275/files) as it was interfering with my  changes (I believe this PR relies on broke selection api in firefox)
3:\
I removed the usage of `setDomSelection`. This is because `setBaseAndExtent` removed all ranges leaving only 1 range (this removed the ability to select more cells)
4:\
I removed the `el.focus()` because it relied on the `setDomSelection`
5:\
The slight refactoring was at some point done by eslint

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.) (I will soon, this will be the next commit)

2023-07-25 19:09 UTC, dylans requested changes
Generally looks fine, we'll land and see if it causes any major regressions.

Could you please fix the minor comment typo (colapsed -> collapsed) and somewhere add a link to an explanation of the issue with Firefox so someone in the future can find the relevant background issue?

2023-07-25 19:16 UTC, WcaleNieWolny commented
> Generally looks fine, we'll land and see if it causes any major regressions.
> 
> and somewhere add a link to an explanation of the issue with Firefox so someone in the future can find the relevant background issue?

Is a link to this PR and the explanation I gave in the initial message okay?

2023-07-26 06:54 UTC, dylans commented
> > Generally looks fine, we'll land and see if it causes any major regressions.
> > and somewhere add a link to an explanation of the issue with Firefox so someone in the future can find the relevant background issue?
> 
> Is a link to this PR and the explanation I gave in the initial message okay?

yes that's fine

2023-07-26 06:55 UTC, WcaleNieWolny commented
So is this ready to be merged?

2023-07-26 06:55 UTC, dylans approved these changes

2023-07-26 12:44 UTC, dylans commented
> So is this ready to be merged?

Our integration tests failed, so I'm running them again to see if it was a service issue or if this has introduced a regression.

2023-07-26 13:07 UTC, WcaleNieWolny commented
> Our integration tests failed, so I'm running them again to see if it was a service issue or if this has introduced a regression.

It did introduced a regression. Just submitted a fix for that

2023-07-26 14:09 UTC, merged