fix: fix wxwork(wechatwork) ime can not work
ianstormtaylor/slate pull request #5496
Opened 2023-08-15 12:38 UTC by evilbs

Description:
Fix cannot input Chinese on wxwork(wechat work).

Example:
wechat and wxwork useragent:
Wechat usearagent:
Mozilla/5.0 (Linux; Android 13; 22127RK46C Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML%2C like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36 XWEB/5127 MMWEBSDK/20230604 MMWEBID/7189 MicroMessenger/8.0.38.2400(0x28002639) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64 qcloudcdn-xinan

wxwork(wexin work) useraget:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.110 Safari/537.36 Language/zh wxwork/4.1.9 (MicroMessenger/6.2) WindowsWechat  MailPlugin_Electron WeMail embeddisk

https://github.com/ianstormtaylor/slate/blob/a25d7a40e5440ee54e4debbf42ed1c12d9e2248a/packages/slate-react/src/components/editable.tsx#L1137
https://github.com/ianstormtaylor/slate/blob/a25d7a40e5440ee54e4debbf42ed1c12d9e2248a/packages/slate-react/src/utils/environment.ts#L56
/.*Wechat/.test(navigator.userAgent)
This regex will also filter the useragent of the wxwork(weixin work), causing the wxwork unable receive the IME CompositionEnd event then cannot input Chinese.

**Checks**
- [x ] The new code matches the existing patterns and styles.
- [x ] The tests pass with `yarn test`.
- [x ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2023-08-15 16:27 UTC, dylans requested changes
@evilbs could you please add a changeset per the guidelines and then we can release this update? Thanks

2023-08-16 02:49 UTC, evilbs commented
@dylans Sure, I will immediately add the changeset according to the guidelines。

2023-08-16 03:19 UTC, evilbs commented
@dylans I have added the changeset. Please review it again. Thank you.

2023-08-16 17:56 UTC, evilbs commented
@ttitoo hi, ttitoo,
Why did you have to disable WeChat? Which platform's WeChat was causing issues?

https://github.com/ianstormtaylor/slate/blob/a25d7a40e5440ee54e4debbf42ed1c12d9e2248a/packages/slate-react/src/utils/environment.ts#L56-L57

2023-08-16 18:49 UTC, evilbs commented
Slate Can't input Chinese correctly and it carshed on wechat(windows wechat/mac wechat/wxwork)
https://github.com/ianstormtaylor/slate/assets/3305041/3c4780f6-f4a7-4303-b55b-829d464a8c5e
![image](https://github.com/ianstormtaylor/slate/assets/3305041/55e4302a-96e0-4b0b-be29-2f4b2c5e35ba)

I fixed it and it ok on wechat(windows wechat/mac wechat/wxwork...)
https://github.com/ianstormtaylor/slate/assets/3305041/c410f1c8-8865-403f-ae2d-00637abae0e4

so i want remove restrictions on wechat.

@dylans pleas review...

2023-08-23 11:44 UTC, dylans commented
@evilbs  It looks like #5497 solves this by excluding macos rather than all platforms. Could you verify if the solution in the other PR works for you or if this is the better solution?

2023-08-27 15:33 UTC, evilbs commented
@dylans PR #5497 doesn't resolve my issue.  it is only resolved mac wechat. my case happend on window wechat browser and window wxwork browser.

https://github.com/ianstormtaylor/slate/assets/3305041/eceeef87-e905-41f1-adbd-443af7af63f1

but i found thast all browsers of wechat products(window wechat/mac wechat/window wxwork/mac wxwork) has save problem.
i remove the restrictions, all wechat borwser can work fine. i checked all platforms and all wechat products.

2023-08-29 11:57 UTC, dylans commented
@evilbs, ok, but in that case it doesn't make sense to completely remove the utility function to check for the Wechat browser, but rather just not to use it here?

2023-08-30 14:56 UTC, evilbs commented
@dylans hi, I restored the utility function.

2024-06-25 11:11 UTC, dylans commented
Apologies, this one fell off my radar. @evilbs if you have time to clean it up, I'll review and land it.

2025-05-05 15:36 UTC, closed without merging