fix: automatically inserts an empty text node after inserting an image
ianstormtaylor/slate pull request #5598
Opened 2024-01-29 23:15 UTC by CaptainCrouton89

**Description**
Automatically adds an empty text node after inserting an image in the example code for using images in Slate. 

**Issue**
Fixes #5597

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2024-02-07 11:35 UTC, dylans approved these changes
Thanks for the fix @CaptainCrouton89

2024-02-07 11:49 UTC, dylans requested changes
@CaptainCrouton89  see the quick suggested changes by Prettier. Thanks.

2024-02-09 12:49 UTC, dylans requested changes
suggested changes from prettier

2024-02-09 12:49 UTC, dylans commented on site/examples/images.tsx
> +    type: "paragraph",
```suggestion
    type: 'paragraph',
```

2024-02-09 12:49 UTC, dylans commented on site/examples/images.tsx
> +    children: [{ text: "" }],
```suggestion
    children: [{ text: '' }],
```

2024-02-09 12:49 UTC, dylans commented on site/examples/images.tsx
> +  });
```suggestion
  })
```

2024-02-09 12:50 UTC, dylans approved these changes

2024-02-09 12:54 UTC, merged

2024-02-09 16:10 UTC, CaptainCrouton89 commented
Thanks for fixing that! Glad it's making it in :)