feat:  add prop enableSelectionOp and onDOMSelectionChangeThrottleTime
ianstormtaylor/slate pull request #5772
Opened 2024-11-29 19:39 UTC by electroluxcode

**Description**
the issue of the anchor, it was discovered that the function for setting the anchor was filtered out during `throttle`. Currently, the default value for this is 100 milliseconds. If it is changed to 0 milliseconds, this problem can be solved.

As for the issue of selection, it can be considered to add a `new type` in the operation name `enableSelectionOp`. This type can be used to determine whether the selection of the collaborator needs to be applied to the co-collaborator.

This pull request mainly adds the passing of two parameters to solve this issue if developer want to resolve the problem like me. and It will not interfere with the original logic.

Finally, the achieved effect is as follows. It can be seen that both the selection and the anchor are as expected.

**Issue**
fix https://github.com/ianstormtaylor/slate/issues/5771

**Example**

https://github.com/user-attachments/assets/86bf9233-e39f-459d-a810-5031c7429cd0

2024-11-29 20:43 UTC, dylans requested changes
Nice improvement and thanks for the explanation.

I don't see an easy way to write an automated test for this, so I'll let that pass for now.

Could you please add a changeset and then I'll land it shortly?

2024-12-07 07:21 UTC, dylans commented on .changeset/lovely-penguins-begin.md
> +"slate-react": patch
```suggestion
'slate-react': patch
```

2024-12-07 07:21 UTC, dylans commented on .changeset/lovely-penguins-begin.md
> +"slate": patch
```suggestion
'slate': patch
```

2024-12-07 17:34 UTC, electroluxcode commented
I have some new ideas for issue1 about https://github.com/ianstormtaylor/slate/issues/5771 . Could you please take a look at this draft? https://github.com/ianstormtaylor/slate/pull/5777.

2025-05-05 15:39 UTC, dylans commented
This is now very stale unfortunately. We can revisit in a new PR if still relevant.

2025-05-05 15:39 UTC, closed without merging